### ISSUE TITLE
TypeError: db.getUrl is not a function

### ISSUE THREAD

**Issue by tyler-johnson** [pouchdb/pouchdb-req-http-query#18]
Since `getUrl()` was removed in 6.0, this library is a bit broken. It seems like `pouchdb-security` uses this library, making it impossible to get/set security documents with `getSecurity()`/`putSecurity()`.

Happy to create a pull-request for this!

**Comment by nolanlawson** [comment]
Given that https://github.com/pouchdb/pouchdb-auth/issues/24 is also affected by this, it seems like it might be useful to write a pouchdb plugin that adds `db.getUrl()`.

As I understand it, `getUrl()` is fully implementable given the information that's already exposed, and if it were available as a plugin, we could just auto-fix existing modules that depend on it.

**Comment by linusthiel** [comment]
I'm looking into this as I want to use [pouchdb-seamless-auth](https://github.com/marten-de-vries/pouchdb-seamless-auth), which is also bitten by this bug (via pouchdb-auth). I found my way here thanks to @marten-de-vries. However, it seems to me to have one more problem than just the deprecated `db.getUrl()`. The way it slices off the database from the url makes it fail if I proxy couchdb under a different path, e.g. the database URL is `https://example.com/couchdb/_users`, with all requests to `/couchdb` being proxied, then the resulting URL will be `https://example.com/_session` instead of the correct `https://example.com/couchdb/_session`. Should I make a try at a fix for this, and also not rely on `db.getUrl()`, or is there another way?

**Comment by marten-de-vries** [comment]
@linusthiel If you can find a fix that respects proxies, that sounds great. That use case probably just never came up so far. Note that there are a lot of tests that you can run to verify a fix if you want - pouchdb-auth, pouchdb-show & pouchdb-list and others all use this and have comprehensive tests.

**Comment by linusthiel** [comment]
Investigating further, the way the URL parsing is done seems to be broken, unless it's relying on the URL always ending with a trailing `/`. Could it be that that was the case with `db.getUrl()`, while `db.name` does not necessarily have the trailing `/`?

**Comment by marten-de-vries** [comment]
Probably, although it's been a while so I'm not sure.

**Comment by linusthiel** [comment]
@marten-de-vries I have looked into it and I think I have a simple fix that should do the trick -- however, I can't seem to get it tested with the projects you mention because they have other tests failing and/or depend on PouchDB 5.x. Should I send a PR anyway or can I do some other changes to get tests to run?

**Comment by marten-de-vries** [comment]
@linusthiel Please send the PR anyway, anything is better than the current broken state. If you want to fix the tests that would be appreciated of course, but I can imagine that takes too much time.
